export default {
  FETCH_PEOPLE_IN_SPACE: 'FETCH_PEOPLE_IN_SPACE',
  FETCH_PEOPLE_IN_SPACE_CACHE_HIT: 'FETCH_PEOPLE_IN_SPACE_CACHE_HIT',
  FETCH_PEOPLE_IN_SPACE_ERROR: 'FETCH_PEOPLE_IN_SPACE_ERROR',
  FETCH_PEOPLE_IN_SPACE_SUCCESS: 'FETCH_PEOPLE_IN_SPACE_SUCCESS',
  FETCH_PICTURE_OF_THE_DAY: 'FETCH_PICTURE_OF_THE_DAY',
  FETCH_PICTURE_OF_THE_DAY_CACHE_HIT: 'FETCH_PICTURE_OF_THE_DAY_CACHE_HIT',
  FETCH_PICTURE_OF_THE_DAY_ERROR: 'FETCH_PICTURE_OF_THE_DAY_ERROR',
  FETCH_PICTURE_OF_THE_DAY_SUCCESS: 'FETCH_PICTURE_OF_THE_DAY_SUCCESS'
}
